version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    container_name: postgresdb
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: contractdb